# Generated by Django 4.1.3 on 2022-11-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='wheight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
