# Generated by Django 4.1.3 on 2022-11-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_good_wheight'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='coef',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
